/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#10141a',
        'surface': '#10141a',
        'surface-container-lowest': '#0a0e14',
        'surface-container-low': '#181c22',
        'surface-container': '#1c2026',
        'surface-container-high': '#262a31',
        'surface-container-highest': '#31353c',
        'surface-bright': '#353940',
        'surface-dim': '#10141a',
        'surface-variant': '#31353c',
        'surface-tint': '#ffb59c',
        'on-surface': '#dfe2eb',
        'on-surface-variant': '#dec0b6',
        'on-background': '#dfe2eb',
        'inverse-surface': '#dfe2eb',
        'inverse-on-surface': '#2d3137',
        'inverse-primary': '#a43c12',
        'outline': '#a68b82',
        'outline-variant': '#57423b',
        'primary': '#ffb59c',
        'primary-container': '#ff7f50',
        'on-primary': '#5c1a00',
        'on-primary-container': '#6c2000',
        'primary-fixed': '#ffdbcf',
        'primary-fixed-dim': '#ffb59c',
        'on-primary-fixed': '#380c00',
        'on-primary-fixed-variant': '#822800',
        'secondary': '#67df70',
        'secondary-container': '#27a640',
        'on-secondary': '#00390d',
        'on-secondary-container': '#00320a',
        'secondary-fixed': '#83fc89',
        'secondary-fixed-dim': '#67df70',
        'on-secondary-fixed': '#002105',
        'on-secondary-fixed-variant': '#005317',
        'tertiary': '#4dd9e4',
        'tertiary-container': '#00b5c0',
        'on-tertiary': '#00363a',
        'on-tertiary-container': '#004145',
        'tertiary-fixed': '#7af4ff',
        'tertiary-fixed-dim': '#4dd9e4',
        'on-tertiary-fixed': '#002022',
        'on-tertiary-fixed-variant': '#004f54',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'panel-header': '56px',
        'panel-footer': '32px',
        'panel-sidebar': '260px',
        'margin-page': '24px',
        'gutter': '16px',
        'unit': '4px',
      },
      fontFamily: {
        'mono-code': ['JetBrains Mono', 'monospace'],
        'headline-xl': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['JetBrains Mono', 'monospace'],
        'headline-sm': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '1.0', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '1.0', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'mono-code': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-xl': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
